AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - 'tmp/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Metrics/ClassLength:
  Max: 150

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Metrics/AbcSize:
  Max: 17
