name: build-rubocop-rspec

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

env:
  COVERAGE: true

jobs:
  build-rubocop-rspec:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec ./spec

      - uses: joshmfrankel/simplecov-check-action@main
        with:
          minimum_suite_coverage: 85
          minimum_file_coverage: 85
          github_token: ${{ secrets.GITHUB_TOKEN }}
